name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Compile LaTeX documentation
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: doc/
          root_file: Num4_Projekt_Maximal_Range_Flight.tex
  build_latex_slides:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Compile LaTeX slides
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: slides/
          root_file: slides_maximal_range_flight.tex